// Auth types
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
//Config types
export const SETLOADERVISIBLE = 'SETLOADERVISIBLE'
//Log 
export const ADDLOG = 'ADDLOG'
export const UPDATELOG = 'UPDATELOG'
export const DELETELOGS = 'DELETELOGS'
export const UPDATEUSER = 'UPDATEUSER'
export const UPDATECURRENTDATE = 'UPDATECURRENTDATE'
export const TRUNCATELOGS = 'TRUNCATELOGS'
export const GETLOGS = 'GETLOGS'
//Machines
export const ADDMACHINES = 'ADDMACHINES'
export const TRUCATEMACHINES = 'TRUCATEMACHINES'
export const UPDATEMACHINESTATE = 'UPDATEMACHINESTATE'
export const DELETEMACHINES = 'DELETEMACHINES'
export const UPDATEMACHINES = 'UPDATEMACHINES'
//Check in and out
export const CHECKIN = "CHECKIN"
export const CHECKOUT = "CHECKOUT"
export const CLEARCHECKIN = "CLEARCHECKIN"
export const CLEARCHECKOUT = "CLEARCHECKOUT"
export const CHECKINAPI = "CHECKINAPI"
export const CHECKOUTAPI = "CHECKOUTAPI"
//Project ManageMent
export const ADDPROJECTS = "ADDPROJECTS"
export const CHANGESTATUSUSER = "CHANGESTATUSUSER"
export const CHANGESTATUSPROJECT = "CHANGESTATUSPROJECT"